### PR TITLE
Add License

### PR DESCRIPTION
**Pull request by rubenvarela**
For copyright holder, I propose "The Contributors" as the copyright holders, akin to Chromium and other projects

> Copyright 2015 The Chromium Authors

https://chromium.googlesource.com/chromium/src/+/master/LICENSE

Hope this looks good to the current contributors, @jamesxv7, @smedina25, @arrancapr, @aallfredo

### CODE REVIEW

**Comment by jamesxv7** [comment]
I think there should be no problem.

**Comment by jamesxv7** [comment]
Why we should use the "The Contributors" license instead of a MIT license or Creative Common?

**Comment by rubenvarela** [comment]
The Pull Request is for an MIT License. Instead of naming everyone, it uses 'The Contributors' as some other projects do.

Can definitely be changed as needed.

**Comment by jamesxv7** [comment]
Didn't notice license used in the files changed, I just review the link in your comment, I'll proceed to merge. Thanks a lot for this contribution.

**Pull request merged**
